[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["contract", "build", "--manifest-path", "contracts/indexer/Cargo.toml"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

